/*
 * This file is generated by jOOQ.
 */
package com.example.bookmanagementsystem.jooq.public_.tables;


import com.example.bookmanagementsystem.jooq.public_.Keys;
import com.example.bookmanagementsystem.jooq.public_.Public;
import com.example.bookmanagementsystem.jooq.public_.tables.Authors.AuthorsPath;
import com.example.bookmanagementsystem.jooq.public_.tables.Books.BooksPath;
import com.example.bookmanagementsystem.jooq.public_.tables.records.AuthorsBooksRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthorsBooks extends TableImpl<AuthorsBooksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.authors_books</code>
     */
    public static final AuthorsBooks AUTHORS_BOOKS = new AuthorsBooks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthorsBooksRecord> getRecordType() {
        return AuthorsBooksRecord.class;
    }

    /**
     * The column <code>public.authors_books.author_id</code>.
     */
    public final TableField<AuthorsBooksRecord, UUID> AUTHOR_ID = createField(DSL.name("author_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.authors_books.book_id</code>.
     */
    public final TableField<AuthorsBooksRecord, UUID> BOOK_ID = createField(DSL.name("book_id"), SQLDataType.UUID.nullable(false), this, "");

    private AuthorsBooks(Name alias, Table<AuthorsBooksRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuthorsBooks(Name alias, Table<AuthorsBooksRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.authors_books</code> table reference
     */
    public AuthorsBooks(String alias) {
        this(DSL.name(alias), AUTHORS_BOOKS);
    }

    /**
     * Create an aliased <code>public.authors_books</code> table reference
     */
    public AuthorsBooks(Name alias) {
        this(alias, AUTHORS_BOOKS);
    }

    /**
     * Create a <code>public.authors_books</code> table reference
     */
    public AuthorsBooks() {
        this(DSL.name("authors_books"), null);
    }

    public <O extends Record> AuthorsBooks(Table<O> path, ForeignKey<O, AuthorsBooksRecord> childPath, InverseForeignKey<O, AuthorsBooksRecord> parentPath) {
        super(path, childPath, parentPath, AUTHORS_BOOKS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AuthorsBooksPath extends AuthorsBooks implements Path<AuthorsBooksRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AuthorsBooksPath(Table<O> path, ForeignKey<O, AuthorsBooksRecord> childPath, InverseForeignKey<O, AuthorsBooksRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AuthorsBooksPath(Name alias, Table<AuthorsBooksRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AuthorsBooksPath as(String alias) {
            return new AuthorsBooksPath(DSL.name(alias), this);
        }

        @Override
        public AuthorsBooksPath as(Name alias) {
            return new AuthorsBooksPath(alias, this);
        }

        @Override
        public AuthorsBooksPath as(Table<?> alias) {
            return new AuthorsBooksPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AuthorsBooksRecord> getPrimaryKey() {
        return Keys.AUTHORS_BOOKS_PKEY;
    }

    @Override
    public List<ForeignKey<AuthorsBooksRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AUTHORS_BOOKS__AUTHORS_BOOKS_AUTHOR_ID_FKEY, Keys.AUTHORS_BOOKS__AUTHORS_BOOKS_BOOK_ID_FKEY);
    }

    private transient AuthorsPath _authors;

    /**
     * Get the implicit join path to the <code>public.authors</code> table.
     */
    public AuthorsPath authors() {
        if (_authors == null)
            _authors = new AuthorsPath(this, Keys.AUTHORS_BOOKS__AUTHORS_BOOKS_AUTHOR_ID_FKEY, null);

        return _authors;
    }

    private transient BooksPath _books;

    /**
     * Get the implicit join path to the <code>public.books</code> table.
     */
    public BooksPath books() {
        if (_books == null)
            _books = new BooksPath(this, Keys.AUTHORS_BOOKS__AUTHORS_BOOKS_BOOK_ID_FKEY, null);

        return _books;
    }

    @Override
    public AuthorsBooks as(String alias) {
        return new AuthorsBooks(DSL.name(alias), this);
    }

    @Override
    public AuthorsBooks as(Name alias) {
        return new AuthorsBooks(alias, this);
    }

    @Override
    public AuthorsBooks as(Table<?> alias) {
        return new AuthorsBooks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorsBooks rename(String name) {
        return new AuthorsBooks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorsBooks rename(Name name) {
        return new AuthorsBooks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorsBooks rename(Table<?> name) {
        return new AuthorsBooks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorsBooks where(Condition condition) {
        return new AuthorsBooks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorsBooks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorsBooks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorsBooks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthorsBooks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthorsBooks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthorsBooks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthorsBooks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorsBooks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorsBooks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
