/*
 * This file is generated by jOOQ.
 */
package com.example.bookmanagementsystem.jooq.public_.tables.records;


import com.example.bookmanagementsystem.jooq.public_.enums.PublicationStatus;
import com.example.bookmanagementsystem.jooq.public_.tables.Books;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BooksRecord extends UpdatableRecordImpl<BooksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.books.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.books.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.books.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.books.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.books.price</code>.
     */
    public void setPrice(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.books.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.books.publication_status</code>.
     */
    public void setPublicationStatus(PublicationStatus value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.books.publication_status</code>.
     */
    public PublicationStatus getPublicationStatus() {
        return (PublicationStatus) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BooksRecord
     */
    public BooksRecord() {
        super(Books.BOOKS);
    }

    /**
     * Create a detached, initialised BooksRecord
     */
    public BooksRecord(UUID id, String title, Integer price, PublicationStatus publicationStatus) {
        super(Books.BOOKS);

        setId(id);
        setTitle(title);
        setPrice(price);
        setPublicationStatus(publicationStatus);
        resetChangedOnNotNull();
    }
}
