/*
 * This file is generated by jOOQ.
 */
package com.example.bookmanagementsystem.jooq.public_;


import com.example.bookmanagementsystem.jooq.public_.tables.Authors;
import com.example.bookmanagementsystem.jooq.public_.tables.records.AuthorsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorsRecord> AUTHORS_PKEY = Internal.createUniqueKey(Authors.AUTHORS, DSL.name("authors_pkey"), new TableField[] { Authors.AUTHORS.ID }, true);
}
