/*
 * This file is generated by jOOQ.
 */
package com.example.bookmanagementsystem.jooq.public_;


import com.example.bookmanagementsystem.jooq.DefaultCatalog;
import com.example.bookmanagementsystem.jooq.public_.tables.Authors;
import com.example.bookmanagementsystem.jooq.public_.tables.AuthorsBooks;
import com.example.bookmanagementsystem.jooq.public_.tables.Books;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.authors</code>.
     */
    public final Authors AUTHORS = Authors.AUTHORS;

    /**
     * The table <code>public.authors_books</code>.
     */
    public final AuthorsBooks AUTHORS_BOOKS = AuthorsBooks.AUTHORS_BOOKS;

    /**
     * The table <code>public.books</code>.
     */
    public final Books BOOKS = Books.BOOKS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Authors.AUTHORS,
            AuthorsBooks.AUTHORS_BOOKS,
            Books.BOOKS
        );
    }
}
