/*
 * This file is generated by jOOQ.
 */
package com.example.bookmanagementsystem.jooq.public_;


import com.example.bookmanagementsystem.jooq.public_.tables.Authors;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.authors</code>.
     */
    public static final Authors AUTHORS = Authors.AUTHORS;
}
