/*
 * This file is generated by jOOQ.
 */
package com.example.bookmanagementsystem.jooq.public_;


import com.example.bookmanagementsystem.jooq.public_.tables.Authors;
import com.example.bookmanagementsystem.jooq.public_.tables.AuthorsBooks;
import com.example.bookmanagementsystem.jooq.public_.tables.Books;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.authors</code>.
     */
    public static final Authors AUTHORS = Authors.AUTHORS;

    /**
     * The table <code>public.authors_books</code>.
     */
    public static final AuthorsBooks AUTHORS_BOOKS = AuthorsBooks.AUTHORS_BOOKS;

    /**
     * The table <code>public.books</code>.
     */
    public static final Books BOOKS = Books.BOOKS;
}
